name: test_app
description: A new Flutter project.
version: 0.0.1+1

publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  copy_with_extension: ^5.0.2
  copy_with_extension_gen: ^5.0.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_bloc: ^8.0.1
  go_router: ^12.0.0
  flutter_secure_storage: 9.0.0
  get_it: ^7.6.4
  get_storage: ^2.1.1
  injectable: ^2.1.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  built_value_generator: ^8.4.4
  flutter_lints: ^1.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  injectable_generator: ^2.1.6
  logger: ^2.0.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
